version: 2.1
orbs:
  node: circleci/node@2.0.1

jobs:
  angular-build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          with-cache: true
          app-dir: ./
      - run:
          name: Build Prod Code
          command: npm run build
  firebase-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          with-cache: true
          app-dir: ./
      - run:
          name: Install Firebase-Tools Packages Global
          command: sudo npm install -g firebase-tools
      - run:
          name: Deploy Prod Code
          command: firebase deploy --only hosting --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  -deploy:
    jobs:
      - angular-build
      - firebase-deploy:
          requires:
            - angular-build
          filters:
            branches:
              only: master
