version: 2.1
orbs:
  node: circleci/node@2.0.1

jobs:
  angular-build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          with-cache: true
          app-dir: ./
      - run:
          name: Build Prod Code
          command: npm run build
  firebase-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          with-cache: true
          app-dir: ./
      - run:
          name: Build Prod Code
          command: npm run build
      - run:
          name: Checkout to functions folder
          command: cd functions
      - node/install-packages:
          with-cache: true
          app-dir: ./functions
      - run:
          name: Deploy Cloud Functions
          command: ./node_modules/.bin/firebase deploy --only functions --token "$FIREBASE_TOKEN"
      - run:
          name: Checkout to root folder
          command: cd ..
      - run:
          name: Deploy Prod Code
          command: ./node_modules/.bin/firebase deploy --only hosting --token "$FIREBASE_TOKEN"

workflows:
  -deploy:
    jobs:
      - angular-build
      - firebase-deploy:
          requires:
            - angular-build
          filters:
            branches:
              only: master
